### ISSUE TITLE
Trojan:Win32/Bearfoos.A!ml - AppData\Roaming\ezytdl\bridge-win32\bridge-win32.exe

### ISSUE THREAD

**Issue by zcraber** [ezytdl/pybridge#2]
After installing [[DEV] 3.0.0-dev.358](https://github.com/sylviiu/ezytdl/releases/tag/3.0.0-dev.358) Microsoft Defender and [Virus Total](https://www.virustotal.com/gui/file/b712e76a6c826529cea12dcdbc0b3f0d2ce0a2b65049012e8c772233c065d394/detection) has detected threats in `bridge-win32.exe` file. Hope this is false positive.

![image](https://github.com/sylviiu/ytdlp-pybridge/assets/61133303/dbf996b3-f5c8-42cf-9cfc-947fca25f88d)

**Comment by sylviiu** [comment]
Sorry for late reply; it's always been a false positive. I've also posted about it over at the [ezytdl repo](https://github.com/sylviiu/ezytdl/issues/41) - seems to be related to the yt-dlp code itself.
